#!/bin/bash

TIMES=1 # How many times will the game run
SCHEME='' # The scheme for 2048

while [ $# -ne 0 ]
do
	# Augument parse
	if [ "$1" = "-h" ]
	then
		echo $0 "[-h] [scheme] [loop-times]"
		echo ""
		echo "Options:"
		echo "-h: Print this message"
		echo ""
		echo "scheme:"
		echo "    none: default scheme"
		echo "    blackwhite: black-to-white color scheme (requires 256 colors)"
		echo "    bluered: blue-to-red color scheme (requires 256 colors)"
		echo ""
		echo "loop-times: How many times would your computer play. Defaults to 1"
		echo ""
		exit 0
	elif [ "$1" -eq "$1" ] 2> /dev/null
	then
		TIMES=$1
	else
		SCHEME=$1
	fi
	shift
done

function gen_input() # Generate strings like "wasdwasd" for 2048
{
	while true
	do
		n=$((($RANDOM*$RANDOM)%4))
		case $n in
			0) echo -n w;;
			1) echo -n a;;
			2) echo -n s;;
			3) echo -n d;;
		esac
	done
}

:>score # Truncate score file

# Main loop
for ((i=0; i<$TIMES; i++))
do
	gen_input | ./2048 $SCHEME  2>> score
done

exit 0

